
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
    ports:
      - 8000:8000
    depends_on:
      - redis
    command: php artisan serve --host=0.0.0.0 --port=8000

  node:
    image: node:20
    container_name: vue_node
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 5173:5173
    command: sh -c "npm install && npm run dev"


  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - 6379:6379